[package]
name = "rust-matlab"
version = "0.1.0"
edition = "2021"

[dependencies]
ndarray = "0.15.6"
nalgebra = "0.29.0"
rulinalg = "0.4.2"
plotters = "0.3.5"
assert_approx_eq = "1.1.0"
approx = "0.5.1"
num-complex = "0.4.3"
